Hyraze/collective-ai-tools

- README.md
added HumataAI,ChatfuelAI,PaintitAI 
---
> feat: :sparkles: added HumataAI,ChatfuelAI,PaintitAI

- CONTRIBUTING.md
updated How to Contribute section of CONTRIBUTING.md
---
> docs: :memo: updated CONTRIBUTING.md

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Added A.I tools in #3D
- [Alpha3D](https://www.alpha3d.io/) - Alpha3D is a revolutionary generative AI-powered platform that transforms 2D images into high-quality 3D assets at scale. #free-trial
- [Pixela AI](https://pixela.ai/) - AI-generated game textures. Share yours with the community! #free
- [StudioGPT by Latent Labs](https://www.latentlabs.art/) - Reimagine Your Visual Designs with AI-Powered Creativity. #paid
---
By submitting this pull request, you confirm that you …
> docs: updated README.md with 3D tools

- README.md
Added kaiber.ai in the image generator section
---
> docs: :memo: added kaiber.ai in image generator section

- README.md
Added Heygen in Video Generator
> docs: 📝 Added heygen in Video Generator

- README.md
Added a link to Dall-E 3 under the Art section to contribute to ai collective tools list!
> Added AI tool link under Art section

- README.md
added Artificial Printer in fashion and sorted the list
---
> docs:  added tools in fashion & sorted list

- README.md
Added links under Education section
> docs: :memo: added links under Education section

- README.md
Added AI tools in Healthcare section
- Added Viz.ai and Enlitic AI tools in Healthcare section
Fixes #19 
---
> Adding AI tools in Healthcare domain

- README.md
added midjourney ai to image generator section
---
> docs: :memo: added midjourney ai to image generator section

- README.md
added resumA.I under resume section
---
> docs: :memo: added resumA.I under resume section

- README.md
Added relume.ai in design section
---
> docs: 📝 added relume.ai in design section

- README.md
Added new tool in Code Assistance and Image generator section.
---
> Docs : Added new tool in Code Assistance and Image generator

- README.md
Added a tool in Email Assistant section
---
> Added a tool in Email Assistant

- README.md
Added tool in Video Generator section
---
> Added tool in Video Generator

- README.md
Tool added in Text-to-Speech section
---
> Tool added in Text-to-Speech section

- README.md
> Docs : Added tool to Chatbots section

- README.md
Added tool in Music section
---
> Docs : Added tool in Music 

- README.md
Added tool in Dating section
---
> Added tool in Dating section

- README.md
Added tool to Developer section
---
> Added tool to Developer section

- README.md
The purpose of this pull request is to enhance the list of AI tools for the Art category, by making a valuable addition to it. This new AI-based image generation tool - "BlueWillow" is easy to use and free.  I added this tool name along with the link to its official website as well as a concise and clear description of it in the specified format.
Changes made:
- [BlueWillow](https://www.bluewillow.ai) - Prompt based AI image generating tool for logos, characters, digital artwork, etc. #free
- [✔] Read and understood the [Contributing Guidelines](CONTRIBUTING.md).
- [✔] Checked that your changes align with the repository's goals and content.
- [✔] The submission is not already present in the list
None.
Not Applicable.
> Added new AI tool in Art section

- index.html
feat: ✨ auto add reference to the urls
#48 done
---
> feat: ✨ auto add reference to the urls

- index.html
fix: :art: update ref link
---
> fix: :art: update ref link

- README.md
I added Qwen as the language model list , this is strong base language models, which have been stably pretrained for up to 3 trillion tokens of multilingual data with a wide coverage of domains, languages (with a focus on Chinese and English), etc. 
- [✔ ] Read and understood the [Contributing Guidelines](CONTRIBUTING.md).
- [✔] Checked that your changes align with the repository's goals and content.
- [✔] The submission is not already present in the list
-
-
---
> add Qwen pretrained large language model proposed by Alibaba Cloud

- README.md
added tools in productivity and summaries
---
> docs: 📝 added tools in productivity and summaries

- README.md
- I have added ai tools in Legal Assistant.
- I have removed an extra #art link from readme.md
---
> docs: 📝 added ai tools in Legal Assistant

- README.md
removed unwanted section added more tools
---
> docs: 📝 removed unwanted section added more tools

- README.md
added tool in image generator
---
> docs: 📝 added tool in image generator

- README.md
- I have added ai tools in Logo Generator.
---
> docs: 📝 added ai tools in Logo Generator

- README.md
This PR adds Pictory AI to the Video Generator 
---
> Add Pictory-AI 

- README.md
Add Candy.ai and DatePlanner.ai in the Dating section
Added two links to the Dating Section
---
> Add Two Links in Dating Section

- README.md
docs: added taskade tool in productivity section.
---
> docs: added taskade tool in productivity section.

- README.md
> added one code assistant

- README.md
> docs: 📝 Added Imagine in Image Generator Section

- README.md
> style: :lipstick: rearranged alphabetically

- README.md
docs: 📝 Added Wepik in Image Generator Section
---
> docs: 📝 Added Wepik in Image Generator Section

- README.md
> feat: :sparkles: added cooking section and added link

- README.md
docs: 📝 Added AI Excel Bot in Spreadsheets Section
---
> docs: 📝 Added AI Excel Bot in Spreadsheets Section

- README.md
I have added new AI resources links and description to the list.
---
> added new AI resources

- README.md
> feat: add stealthGPT tool

- README.md
> feat: add 3dfy in 3d section

- README.md
docs: 📝 added new section design generator and tool
---
> docs: 📝 added new section design generator and tool

- README.md
docs: added photo generator tool in photo generator section
---
> docs: added photo generator tool in a new photo generator section.

- README.md
Added Picsart in  Image Generator section
---
> Added Picsart in  Image Generator section

- README.md
> Added SQL AI Tool

- README.md
The purpose of this pull request is to addition of couple of AI tools which can be used for design generation.
This commit will add AI tools for design generator. Those are,
1. [Canva](https://www.canva.com/)
2. [Designs AI](https://designs.ai/)
Suraj Khamkar
khamkarsuraj.b@gmail.com
---
> Add: Canva and Designs AI

- README.md
The purpose of this PR is to addition of couple of AI Audio Editing tools. 
This PR will add 2 new AI Audio Editing tools to the list.
[CrystalSound](https://crystalsound.ai/)
[Gladia](https://www.gladia.io/)
> Add: CrystalSound and Gladia

- README.md
Added an AI coding assistance in the chatbot section. It's called Phind.
Relates to #34
---
> Added Phind in Chatbot section

- README.md
Added new tool that helps us to remove background of any images and  replace  with other.
very helpful ai tool that is remove.bg
> added new tools

- README.md
fixed - fitness item was in finance
---
> item added in wrong category

- README.md
> Adding Dating AI

- README.md
> Adding svg generating tool 

- README.md
> Adding Video Generator AI

- README.md
> Adding Code-assistant AI

- README.md
Added a new site to the Dating section with extra functionalities compared to others.
None
None
---
> Update README.md Dating section

- README.md
> Adding Design Generator AI

- README.md
VSDECO tool added to the list.
---
> added vsdeco tool

- README.md
Adding Floom: AI gateway and marketplace for developers, enables streamlined integration of AI features into products
---
> Adding Floom

- README.md
Add https://fliki.ai/ - text to video generator
Add https://wonderplan.ai/ - personal trip planner
- [ x] Read and understood the [Contributing Guidelines](CONTRIBUTING.md).
- [ x] Checked that your changes align with the repository's goals and content.
- [ x] The submission is not already present in the list
---
> Add fliki.ai and wonderplan.ai

- README.md
This adds two new educational chatbot tools: Text With Authors and Text With History, which are freemium. Also updates the related Text With Jesus to reflect its freemium status.
> Added Text With History and Text With Authors

- README.md
Add Family travel AI app Famxplor
None
None
---
> Add Travel / Famxplor

- README.md
> Update Summarize Chatpulse

- README.md
> Adding a Productivity Tool

- README.md
> Add IDPhoto.ai

- README.md
> Add myGiftAgent

- README.md
> Add excelmatica.com and quizb.ai to list

- README.md
Feat: added Keploy.io in ai tools for automation. Keploy is a tool used for automated api and unit testing. Keploy has a vs code extension that can be used for single click automated test generation and a unit test pr agent that generates unit tests after each change and pr using diff algorithms
Added Keploy.io in ai tools for automation. Keploy is a tool used for automated api and unit testing. Keploy has a vs code extension that can be used for single click automated test generation and a unit test pr agent that generates unit tests after each change and pr using diff algorithms
If this pull request resolves or is related to any issues, please mention them here using the following format: "Fixes #123" …
> feat: added keploy as an ai tool/assistant

- README.md
Add 2 tools in Image Editing and Dating sections.
---
> Add 2 tools to README.md

- README.md
Added SummaryTube in list of awesome AI tools
SummaryTube helps you save time and create AI powered smart video summaries for any YouTube video for FREE. Generate video summaries, key moments and transcripts for any YouTube video easily. Users can promote Youtube content for free by generating and sharing beautiful video summaries with users. Browse easily through your saved video summaries anytime in your account. Use chrome extension to summarize directly on Youtube. Get key insights & transcripts from youtube video, Q&A & save/share summaries easily.
If this pull request resolves or is related to any issues, …
> Update README.md : Add SummaryTube in AI tool list

- README.md
Added interiorvibes.co to the real estate category.
InteriorVibes is a Virtual Staging solution for real estate agencies that transform empty rooms into beautifully staged spaces using AI. Just upload a photo of any room, select a room, and get stunning, photorealistic visuals in seconds.
---
By submitting this pull request, you confirm that you have read and agree to abide by the [Code of Conduct](CODE_OF_CONDUCT.md) and the [Contributing Guidelines](CONTRIBUTING.md) of the AI …
> added interiorvibes.co to readme

- README.md
- Change FOSSA status badge URL to reflect new repository name
- Update Product Hunt link to match rebranded project name
---
> fix: update FOSSA badge and Product Hunt link in README.md

- README.md
- index.tsx
- Implement addTrackingParams function to append UTM parameters and referrer tracking to external URLs.
- Add trackClick function to log click events for analytics.
- Update tool card, buttons, and footer links to utilize new tracking functions for improved analytics.
- Enhance README.md with additional AI tools and descriptions for better resource visibility.
> feat: enhance tracking and analytics for external links

- README.md
Added virtualstagingexpert.com to the readme file
---
> add virtualstagingexpert to real estate category

- README.md
Adding the new feature DocsGPT to Customer Support
---
> feat: Add [DocsGPT] to [Customer Support]

- README.md
Remove Bard as it is outdated, and added replacement to it.
---
> Update chatbot list in README.md

- README.md
This pull request adds two new AI tools to the repository:
1. Wand AI (Startup Tools category) - An AI operating system to build, manage, and collaborate with autonomous agents that automate business processes for a hybrid human+AI workforce.
2. VoiceBit (Customer Support category) - A 24/7 AI phone assistant for small businesses and restaurants that answers calls, manages inquiries, and ensures no customer call is missed.
NA
- Wand AI is a freemium tool (#freemium).
- VoiceBit appears to be primarily paid (subscription/usage-based), so it is tagged with #customersupport and #smallbusiness.
---
By submitting this pull request, you confirm that you have read and agree to abide by the [Code of …
> feat: Add [WandAI & VoiceBitAI] to [Startup tools & Customer Support]
